---
user: false
organizations:
  - vivitInc
labels:
  - name: 'Don''t Merge'
    description: 'DON''T MERGE!!'
    color: 'e5171f'

  - name: 'Failed Tests'
    description: '自動マージテスト失敗'
    color: 'e5171f'

  - name: 'Status: In Progress'
    description: '作業中'
    color: '0079c2'

  - name: 'Status: Rebase Needed'
    description: 'rebase or masterマージが必要'
    color: '814721'

  - name: 'Status: Release Waiting'
    description: 'リリース待ち'
    color: '0e6a6d'

  - name: 'Status: Review Needed'
    description: 'レビューください'
    color: 'b6007a'

  - name: 'Type: Bug'
    description: 'バグ修正'
    color: 'fef263'

  - name: 'Type: Documentation'
    description: 'ドキュメントの修正'
    color: 'f9c0df'

  - name: 'Type: Feature'
    description: '機能追加'
    color: 'bad7fc'

  - name: 'Type: Maintenance'
    description: '既存コードの修正'
    color: 'd0f9a9'

  - name: 'Type: Refactoring'
    description: 'リファクタリング'
    color: 'f9d381'
