---
organizations:
  - vivitInc
user: false
labels:
  - name: 'Status: Abandoned'
    color: '888084'
    description: '却下'
  - name: 'Status: In Progress'
    color: 'a2d7dd'
    description: '作業中'
  - name: 'Status: PR Welcome'
    color: '007bbb'
    description: 'ツッコミ歓迎'
  - name: 'Status: Proposal'
    color: 'dbd0e6'
    description: '提案'
  - name: 'Status: Release Waiting'
    color: 'ffec47'
    description: 'リリース待ち'
  - name: 'Status: Review Needed'
    color: 'b44c97'
    description: 'レビューください'
  - name: 'Type: Breaking Change'
    color: 'd3381c'
    description: '破壊的な変更(マージ注意)'
  - name: 'Type: Bug'
    color: 'fef263'
    description: 'バグ修正'
  - name: 'Type: Do Not Merge'
    color: 'e60033'
    description: 'DON''T MERGE!!'
  - name: 'Type: Documentation'
    color: 'cca6bf'
    description: 'ドキュメントの修正'
  - name: 'Type: Duplicate'
    color: 'afafb0'
    description: '重複'
  - name: 'Type: Feature'
    color: '89c3eb'
    description: '機能追加'
  - name: 'Type: Maintenance'
    color: 'aacf53'
    description: '既存コードの修正'
  - name: 'Type: Refactoring'
    color: 'e0ebaf'
    description: 'リファクタリング'
